
weather:
  # 공공데이터 API KEY
  apikey: 01hXuOcwgTo8a6g4AIpQLW7RYpmLcATl2OcGuzUHEc4oYQ1sSXd7b1etdhb908cP4QZUlqAWz4O+moUQH1o2kg==

# jwt 키값 설정(어느 정도 길이를 가져야 함)
jwt:
  secret: hihihellohello423hellohello3214321sadgfpods51akfopdskapohjpodsafjpods

cloud:
  aws:
    s3:
      bucket: damda
    stack:
      auto: false
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      accessKey: AKIA33AM3NLQ3TBJ646C
      secretKey: 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


