
weather:
  # 공공데이터 API KEY
  apikey: "01hXuOcwgTo8a6g4AIpQLW7RYpmLcATl2OcGuzUHEc4oYQ1sSXd7b1etdhb908cP4QZUlqAWz4O%2BmoUQH1o2kg%3D%3D"

# jwt 키값 설정(어느 정도 길이를 가져야 함)
jwt:
  secret: hihihellohello423hellohello3214321sadgfpods51akfopdskapohjpodsafjpods