spring:
  mvc:
    static-path-pattern: /uploads/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i9b210.p.ssafy.io:7777/damda?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: b210shinchanghak

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate.format_sql: false
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  #Personal Information Management(.ignore)
  profiles:
    include: secret

  AdminMail:
#    id: "damdaCop"
#    password: "vizahyecgncvsdch"
    id: "damdaCop1"
    password: "dpcsrjoggcjzwuct"

  mail:
    smtp:
      auth: true
      starttls:
        required: true
        enable: true
      socketFactory:
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
        port: 465
      port: 465


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9292106e6bff609d98bd0df4de1ede06
            client-secret: GcveX0t6jBVJV3TT7XOxrFAc13inJUYf
            scope:
              - account_email
              - profile_nickname
              - profile_image
            authorization-grant-type: authorization_code
            redirect-uri: https://i9b210.p.ssafy.io/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  web:
    resources:
      static-locations: file:/C:/new/

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org.hibernate.SQL: error